services:
  postgres:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'djffkdlsal1234'
      TZ: 'Asia/Seoul'
    volumes:
      - ./database:/var/lib/mysql
